---

- name: Configure FortiGate logs
  fortios_log_setting:
    vdom: root
    log_setting:
      fwpolicy_implicit_log: enable
      log_invalid_packet: enable
      resolve_ip: enable
      resolve_port: enable

- name: Configure log event filters
  fortios_log_eventfilter:
    vdom: root
    log_eventfilter:
      endpoint: enable
      event: enable
      router: enable
      security_rating: enable
      system: enable
      user: enable
      vpn: enable

- name: Enable syslog forwarding
  fortios_log_syslogd_setting:
    vdom: root
    log_syslogd_setting:
      mode: udp
      port: 514
      server: 10.10.10.2
      status: enable
