---

- name: External Zone
  fortios_system_zone:
    vdom: root
    state: present
    system_zone:
      interface:
        interface_name: port2
        intrazone: allow
        name: EXT

- name: Enterprise LAN
  fortios_system_zone:
    vdom: root
    state: present
    system_zone:
      interface:
        interface_name: port3
        intrazone: allow
        name: LAN
#
#- name: ExtDMZ Zone
#  panos_zone:
#    provider: '{{ provider }}'
#    zone: 'ExtDMZ'
#    mode: 'layer3'
#    interface: ['ethernet1/3']
#
#- name: SOC Zone
#  panos_zone:
#    provider: '{{ provider }}'
#    zone: 'SOC'
#    mode: 'layer3'
#    interface: ['ethernet1/4']
#
#- name: IntDMZ Zone
#  panos_zone:
#    provider: '{{ provider }}'
#    zone: 'IntDMZ'
#    mode: 'layer3'
#    interface: ['ethernet1/5']
#
#- name: Configure virtual router
#  panos_virtual_router:
#    provider: '{{ provider }}'
#    name: 'router'
#    interface: ['ethernet1/1','ethernet1/2','ethernet1/3','ethernet1/4','ethernet1/5']
