---

- name: Configure default route
  fortios_router_static:
    vdom: root
    state: present
    router_static:
      priority: 1
      dst: 0.0.0.0/0
      gateway: 10.10.20.2
      device: port3
